title: Wiring a single LED
hero_image: images/banner.png
description: single-led-wiring description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
