title: Câbler une seule LED
hero_image: images/banner.png
description: Comment câbler une seule LED à un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - 
    title: Câbler une seule LED
